jobs:
    - job: Build_PS_Win2016
      pool:
          vmImage: vs2017-win2016
      steps:
          - powershell: |
                Install-Module -Name Pester -Repository PSGallery -Force -SkipPublisherCheck
                .\PSBlackListChecker.Tests.ps1 $(TEAMSPESTERID) $(SLACKPESTERID) $(DISCORDURL)
            displayName: "Run Pester Tests - PowerShell 5"
          - script: |
                pwsh -c '.\PSBlackListChecker.Tests.ps1' $(TEAMSPESTERID) $(SLACKPESTERID) $(DISCORDURL)
            displayName: "Run Pester Tests - PowerShell 6"

    - job: Build_PSCore_Ubuntu1604
      pool:
          vmImage: ubuntu-16.04
      steps:
          - script: |
                curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
                curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
                sudo apt-get update
                sudo apt-get install -y powershell
            displayName: "Install PowerShell Core"
          - script: |
                pwsh -c '.\PSBlackListChecker.Tests.ps1' $(TEAMSPESTERID) $(SLACKPESTERID) $(DISCORDURL)
            displayName: "Run Pester Tests"

    - job: Build_PSCore_MacOS1013
      pool:
          vmImage: xcode9-macos10.13
      steps:
          - script: |
                brew update
                brew tap caskroom/cask
                brew install mono-libgdiplus
                brew cask install powershell
            displayName: "Install PowerShell Core"
          - script: |
                pwsh -c '.\PSBlackListChecker.Tests.ps1' $(TEAMSPESTERID) $(SLACKPESTERID) $(DISCORDURL)
            displayName: "Run Pester Tests"
